"""Add document_id to conversations

Revision ID: 8d5b61981020
Revises: b51c187fbcc5
Create Date: 2026-07-20 14:20:20.715509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d5b61981020'
down_revision: Union[str, Sequence[str], None] = 'b51c187fbcc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('document_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_conversations_document_id'), 'conversations', ['document_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_document_id'), table_name='conversations')
    op.drop_column('conversations', 'document_id')
    # ### end Alembic commands ###
