"""add medbridge schema and user columns

Revision ID: 94909a40038a
Revises: 
Create Date: 2026-06-24 18:14:23.605799

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '94909a40038a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('users', sa.Column('role', sa.String(), nullable=False, server_default='patient'))
    #op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('users', 'created_at')
    #op.drop_column('users', 'role')
    # ### end Alembic commands ###
